# Generated by Django 5.1.4 on 2024-12-19 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprise', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEnterprise',
            fields=[
                ('ue_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=50)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_users', to='enterprise.enterprise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_enterprises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Enterprise',
                'verbose_name_plural': 'User Enterprises',
                'db_table': 'user_enterprise',
            },
        ),
    ]
