# Generated by Django 5.1.4 on 2025-01-01 22:36

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_enterprise', '0002_userenterprise_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userenterprise',
            name='accept_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Invitation Accepted At'),
        ),
        migrations.AddField(
            model_name='userenterprise',
            name='send_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Invitation Sent At'),
        ),
        migrations.AddField(
            model_name='userenterprise',
            name='token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
