# Generated by Django 5.1.4 on 2025-01-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "user_enterprise",
            "0003_userenterprise_accept_at_userenterprise_send_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userenterprise",
            name="percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Porcentagem do sócio na empresa",
            ),
        ),
    ]
