# Generated by Django 5.1.4 on 2025-02-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_enterprise', '0004_userenterprise_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userenterprise',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True, verbose_name='Porcentagem do sócio na empresa'),
        ),
    ]
