# Generated by Django 5.1.4 on 2025-02-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_ethnicity_alter_user_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='education_level',
            field=models.CharField(blank=True, choices=[('Sem escolaridade', 'Sem escolaridade'), ('Ensino Fundamental', 'Ensino Fundamental'), ('Ensino Médio', 'Ensino Médio'), ('Graduação', 'Graduação'), ('Especialização', 'Especialização'), ('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado'), ('Pós-Doutorado', 'Pós-Doutorado')], max_length=255, null=True),
        ),
    ]
