# Generated by Django 5.1.4 on 2025-02-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_user_education_level_alter_user_ethnicity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='weekly_hours_worked',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
