# Generated by Django 5.1.4 on 2025-02-12 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_user_weekly_hours_worked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='weekly_hours_worked',
        ),
    ]
