# Generated by Django 5.1.4 on 2024-12-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('enterprise_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('problem', models.TextField()),
                ('solution', models.TextField()),
                ('value_proposition', models.TextField()),
                ('differential', models.TextField()),
                ('competitors', models.TextField()),
                ('product', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('mail', models.EmailField(blank=True, max_length=255, null=True)),
                ('linkedin', models.URLField(blank=True, max_length=255, null=True)),
                ('name_foment', models.CharField(blank=True, max_length=255, null=True)),
                ('programm', models.CharField(blank=True, max_length=255, null=True)),
                ('invested', models.BooleanField(default=False)),
                ('boosting', models.BooleanField(default=False)),
                ('value_invested', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('value_foment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('field', models.CharField(max_length=255)),
            ],
        ),
    ]
