# Generated by Django 5.1.4 on 2024-12-19 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_enterprise_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enterprise',
            old_name='profile_picture',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='field',
        ),
    ]
