# Generated by Django 5.1.4 on 2025-01-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0003_rename_profile_picture_enterprise_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='linkedin',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='mail',
            field=models.EmailField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='name_foment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='product',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='programm',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
