# Generated by Django 5.1.4 on 2025-01-29 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0004_alter_enterprise_linkedin_alter_enterprise_mail_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enterprise",
            name="value_foment",
        ),
        migrations.RemoveField(
            model_name="enterprise",
            name="value_invested",
        ),
        migrations.CreateModel(
            name="CompanyMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_recorded",
                    models.DateField(help_text="Data de registro das métricas"),
                ),
                (
                    "team_size",
                    models.IntegerField(help_text="Tamanho do time que não são sócios"),
                ),
                (
                    "revenue_period",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Receita durante o período",
                        max_digits=12,
                    ),
                ),
                (
                    "total_clients",
                    models.IntegerField(
                        help_text="Número total de clientes durante o período"
                    ),
                ),
                (
                    "new_clients",
                    models.IntegerField(
                        help_text="Número de novos clientes durante o período"
                    ),
                ),
                (
                    "investment_round_open",
                    models.BooleanField(
                        help_text="A empresa está com rodada de investimento aberta?"
                    ),
                ),
                (
                    "capital_needed",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Necessidade de capital caso a rodada esteja aberta",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "value_invested",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "value_foment",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "valuation",
                    models.CharField(
                        help_text="Valor estimado do negócio (ou escreva NÃO SEI)",
                        max_length=255,
                    ),
                ),
                (
                    "enterprise",
                    models.ForeignKey(
                        help_text="Empresa associada às métricas",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="enterprise.enterprise",
                    ),
                ),
            ],
        ),
    ]
