# Generated by Django 5.1.4 on 2025-01-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0005_remove_enterprise_value_foment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enterprise",
            name="description",
        ),
        migrations.RemoveField(
            model_name="enterprise",
            name="differential",
        ),
        migrations.RemoveField(
            model_name="enterprise",
            name="mail",
        ),
        migrations.RemoveField(
            model_name="enterprise",
            name="name_foment",
        ),
        migrations.RemoveField(
            model_name="enterprise",
            name="programm",
        ),
        migrations.AddField(
            model_name="enterprise",
            name="accelerated",
            field=models.BooleanField(
                default=False, help_text="Informe se já foi acelerada"
            ),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="accelerator_name",
            field=models.CharField(
                blank=True,
                help_text="Informe o nome da aceleradora",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="business_model",
            field=models.CharField(
                blank=True,
                help_text="Selecione o modelo de negócio",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="city",
            field=models.CharField(
                blank=True, help_text="Informe a cidade", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="client_type",
            field=models.CharField(
                blank=True,
                help_text="Selecione o tipo de cliente",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="cnpj",
            field=models.CharField(
                blank=True,
                help_text="Informe o CNPJ caso sua empresa possua um",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="competitive_differential",
            field=models.TextField(
                default="Não especificado",
                help_text="Descreva o benefício único oferecido ao cliente",
            ),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="discovered_startup",
            field=models.CharField(
                blank=True,
                help_text="Onde conheceu o Programa Startup Piauí",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Principal email e ponto de contato",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="foundation_year",
            field=models.IntegerField(
                blank=True,
                help_text="Informe o ano em que sua startup foi fundada",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="funding_program",
            field=models.CharField(
                blank=True,
                help_text="Especifique o programa ou instituição de fomento",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="funding_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Informe o valor recebido de fomento",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="instagram",
            field=models.URLField(
                blank=True,
                help_text="Digite o endereço completo do Instagram",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="investment_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Informe o valor total do investimento",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="market",
            field=models.CharField(
                blank=True,
                help_text="Selecione o mercado que sua startup atua",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="other_projects",
            field=models.TextField(
                blank=True,
                help_text="Informe outros projetos do Programa Startup Piauí que você participa",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="product_stage",
            field=models.CharField(
                blank=True,
                help_text="Selecione o estágio em que seu produto se encontra",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="revenue_model",
            field=models.CharField(
                blank=True,
                help_text="Selecione o modelo de receita",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="segment",
            field=models.CharField(
                blank=True,
                help_text="Escreva o mercado inicial da sua startup",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="state",
            field=models.CharField(
                blank=True, help_text="Selecione o estado", max_length=2, null=True
            ),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="summary",
            field=models.TextField(
                blank=True,
                help_text="Faça um breve resumo sobre sua empresa ou projeto",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="website",
            field=models.URLField(
                blank=True,
                help_text="Digite o endereço do site da sua startup",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="whatsapp",
            field=models.CharField(
                blank=True,
                help_text="Digite o número do WhatsApp",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="boosting",
            field=models.BooleanField(
                default=False, help_text="Informe se recebeu fomento"
            ),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="competitors",
            field=models.TextField(
                help_text="Conte quem são seus principais competidores ou substitutivos"
            ),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="file",
            field=models.ImageField(
                blank=True,
                help_text="Envie um arquivo relacionado à startup",
                null=True,
                upload_to="enterprise_files/",
            ),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="invested",
            field=models.BooleanField(
                default=False, help_text="Informe se já recebeu investimento"
            ),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="linkedin",
            field=models.URLField(
                blank=True,
                help_text="Digite o endereço completo do LinkedIn",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="name",
            field=models.CharField(
                help_text="Digite o nome da sua startup", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="problem",
            field=models.TextField(
                help_text="Descreva o problema que sua startup resolve"
            ),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="product",
            field=models.CharField(
                help_text="Nos fale sobre seu produto e suas principais funcionalidades",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="solution",
            field=models.TextField(
                help_text="Descreva brevemente a solução oferecida pela sua startup"
            ),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="value_proposition",
            field=models.TextField(
                help_text="Explique de forma breve os benefícios que sua startup oferece"
            ),
        ),
    ]
