# Generated by Django 5.1.4 on 2025-01-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0006_remove_enterprise_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="enterprise",
            name="differential",
            field=models.TextField(
                blank=True, help_text="Diferencial competitivo da startup", null=True
            ),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="Envie uma imagem de perfil da startup",
                null=True,
                upload_to="enterprise_profiles/",
            ),
        ),
    ]
