# Generated by Django 5.1.4 on 2025-01-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0007_enterprise_differential_enterprise_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enterprise",
            name="differential",
            field=models.TextField(
                blank=True,
                help_text="Diferencial competitivo da startup",
                max_length=255,
                null=True,
            ),
        ),
    ]
