# Generated by Django 5.1.4 on 2025-01-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0008_alter_enterprise_differential"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enterprise",
            name="competitive_differential",
            field=models.TextField(
                default="Não especificado",
                help_text="Descreva o benefício único oferecido ao cliente",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="competitors",
            field=models.TextField(
                help_text="Conte quem são seus principais competidores ou substitutivos",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="file",
            field=models.ImageField(
                blank=True,
                help_text="Envie um arquivo relacionado à startup",
                max_length=255,
                null=True,
                upload_to="enterprise_files/",
            ),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="problem",
            field=models.TextField(
                help_text="Descreva o problema que sua startup resolve", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="solution",
            field=models.TextField(
                help_text="Descreva brevemente a solução oferecida pela sua startup",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="summary",
            field=models.TextField(
                blank=True,
                help_text="Faça um breve resumo sobre sua empresa ou projeto",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="value_proposition",
            field=models.TextField(
                help_text="Explique de forma breve os benefícios que sua startup oferece",
                max_length=255,
            ),
        ),
    ]
