# Generated by Django 5.1.4 on 2025-01-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0009_alter_enterprise_competitive_differential_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enterprise",
            name="profile_picture",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
