# Generated by Django 5.1.4 on 2025-01-31 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0011_alter_enterprise_competitive_differential_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companymetrics",
            name="date_recorded",
            field=models.DateField(
                auto_now_add=True, help_text="Data de registro das métricas"
            ),
        ),
    ]
