# Generated by Django 5.1.4 on 2025-02-02 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0012_alter_companymetrics_date_recorded'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_collected', models.DateField(help_text='Data de coleta dos dados')),
                ('responsible', models.CharField(help_text='Responsável pelo dado', max_length=255)),
                ('data_type', models.CharField(choices=[('TRL 0 - Não iniciado', 'TRL 0 - Não iniciado'), ('TRL 1 - Princípios básicos observados e documentados', 'TRL 1 - Princípios básicos observados e documentados'), ('TRL 2 - Formulação do conceito da tecnologia', 'TRL 2 - Formulação do conceito da tecnologia'), ('TRL 3 - Prova de conceito experimental', 'TRL 3 - Prova de conceito experimental'), ('TRL 4 - Validação do conceito em laboratório', 'TRL 4 - Validação do conceito em laboratório'), ('TRL 5 - Validação do conceito em ambiente relevante', 'TRL 5 - Validação do conceito em ambiente relevante'), ('TRL 6 - Demonstração em ambiente relevante', 'TRL 6 - Demonstração em ambiente relevante'), ('TRL 7 - Demonstração em ambiente operacional', 'TRL 7 - Demonstração em ambiente operacional'), ('TRL 8 - Sistema completo e qualificado', 'TRL 8 - Sistema completo e qualificado'), ('TRL 9 - Sistema comprovado em ambiente operacional', 'TRL 9 - Sistema comprovado em ambiente operacional')], help_text='Tipo de dado', max_length=255)),
                ('mit_phase', models.CharField(choices=[('Fase 1', 'Fase 1'), ('Fase 2', 'Fase 2'), ('Fase 3', 'Fase 3')], help_text='Fase do MIT', max_length=255)),
                ('product_status', models.CharField(choices=[('Não Iniciado', 'Não Iniciado'), ('Em Desenvolvimento', 'Em Desenvolvimento'), ('Finalizado', 'Finalizado')], help_text='Status do produto', max_length=255)),
                ('business_status', models.CharField(choices=[('Procurando Equipe', 'Procurando Equipe'), ('Ideação', 'Ideação'), ('MVP', 'MVP'), ('Primeiros Testes', 'Primeiros Testes'), ('Fase Beta', 'Fase Beta'), ('Monetização', 'Monetização'), ('Criação de Clientes', 'Criação de Clientes'), ('Construção de Empresa', 'Construção de Empresa'), ('Scale Up', 'Scale Up')], help_text='Status do negócio', max_length=255)),
                ('how_we_can_help', models.TextField(blank=True, help_text='Como podemos ajudar?', max_length=500, null=True)),
                ('next_steps', models.TextField(blank=True, help_text='Próximos passos', max_length=500, null=True)),
                ('next_meeting_date', models.DateField(blank=True, help_text='Data da próxima agenda', null=True)),
                ('observations', models.TextField(blank=True, help_text='Observações sobre a empresa', max_length=500, null=True)),
                ('enterprise', models.ForeignKey(help_text='Empresa associada ao prontuário', on_delete=django.db.models.deletion.CASCADE, related_name='records', to='enterprise.enterprise')),
            ],
        ),
    ]
