# Generated by Django 5.1.4 on 2025-02-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0013_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='initial_maturity',
            field=models.CharField(blank=True, choices=[('TRL 0 - Não iniciado', 'TRL 0 - Não iniciado'), ('TRL 1 - Princípios básicos observados e documentados', 'TRL 1 - Princípios básicos observados e documentados'), ('TRL 2 - Formulação do conceito da tecnologia', 'TRL 2 - Formulação do conceito da tecnologia'), ('TRL 3 - Prova de conceito experimental', 'TRL 3 - Prova de conceito experimental'), ('TRL 4 - Validação do conceito em laboratório', 'TRL 4 - Validação do conceito em laboratório'), ('TRL 5 - Validação do conceito em ambiente relevante', 'TRL 5 - Validação do conceito em ambiente relevante'), ('TRL 6 - Demonstração em ambiente relevante', 'TRL 6 - Demonstração em ambiente relevante'), ('TRL 7 - Demonstração em ambiente operacional', 'TRL 7 - Demonstração em ambiente operacional'), ('TRL 8 - Sistema completo e qualificado', 'TRL 8 - Sistema completo e qualificado'), ('TRL 9 - Sistema comprovado em ambiente operacional', 'TRL 9 - Sistema comprovado em ambiente operacional')], max_length=255, null=True),
        ),
    ]
