# Generated by Django 5.1.4 on 2025-02-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0014_enterprise_initial_maturity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='responsible',
        ),
        migrations.AddField(
            model_name='record',
            name='responsible_person',
            field=models.CharField(default='Admin', help_text='Nome do responsável pelo dado', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='discovered_startup',
            field=models.CharField(blank=True, choices=[('Fui numa imersão do Programa', 'Fui numa imersão do Programa'), ('Campus Party', 'Campus Party'), ('Investe Nelas 1', 'Investe Nelas 1'), ('Investe Nelas 2', 'Investe Nelas 2'), ('Expo Favela 2023', 'Expo Favela 2023'), ('Expo Favela 2024', 'Expo Favela 2024'), ('Achei no Google', 'Achei no Google'), ('Mídias Sociais', 'Mídias Sociais'), ('Indicação', 'Indicação'), ('Evento do Startup Piauí', 'Evento do Startup Piauí'), ('Outros', 'Outros')], help_text='Onde conheceu o programa?', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='initial_maturity',
            field=models.CharField(blank=True, choices=[('Procurando Equipe', 'Procurando Equipe'), ('Ideação (Modelando produto, sem MVP)', 'Ideação (Modelando produto, sem MVP)'), ('MVP', 'MVP'), ('Primeiros testes (até 5 clientes)', 'Primeiros testes (até 5 clientes)'), ('Fase Beta de Negócio (menos que 20 clientes)', 'Fase Beta de Negócio (menos que 20 clientes)'), ('Monetização (Faturamento > 10k, mais que 20 clientes, 1 recompra)', 'Monetização (Faturamento > 10k, mais que 20 clientes, 1 recompra)'), ('Criação de clientes (Faturamento > 30k em 3 meses)', 'Criação de clientes (Faturamento > 30k em 3 meses)'), ('Construção de empresa (Faturamento > 1mi / 12 meses OU > 100k 3 meses OU investimento > 1mi)', 'Construção de empresa (Faturamento > 1mi / 12 meses OU > 100k 3 meses OU investimento > 1mi)'), ('Scale Up', 'Scale Up')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='product_stage',
            field=models.CharField(blank=True, choices=[('TRL 0 - Não iniciado', 'TRL 0 - Não iniciado'), ('TRL 1 - Princípios básicos observados e documentados', 'TRL 1 - Princípios básicos observados e documentados'), ('TRL 2 - Formulação do conceito da tecnologia', 'TRL 2 - Formulação do conceito da tecnologia'), ('TRL 3 - Prova de conceito experimental', 'TRL 3 - Prova de conceito experimental'), ('TRL 4 - Validação do conceito em laboratório', 'TRL 4 - Validação do conceito em laboratório'), ('TRL 5 - Validação do conceito em ambiente relevante', 'TRL 5 - Validação do conceito em ambiente relevante'), ('TRL 6 - Demonstração em ambiente relevante', 'TRL 6 - Demonstração em ambiente relevante'), ('TRL 7 - Demonstração em ambiente operacional', 'TRL 7 - Demonstração em ambiente operacional'), ('TRL 8 - Sistema completo e qualificado', 'TRL 8 - Sistema completo e qualificado'), ('TRL 9 - Sistema comprovado em ambiente operacional', 'TRL 9 - Sistema comprovado em ambiente operacional')], help_text='Selecione o estágio em que seu produto se encontra', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='data_type',
            field=models.CharField(choices=[('Dever de casa', 'Dever de casa'), ('Intel', 'Intel'), ('Recebemos pedido', 'Recebemos pedido'), ('Follow', 'Follow'), ('Reunião de Conselho', 'Reunião de Conselho'), ('Reunião de Acompanhamento', 'Reunião de Acompanhamento')], help_text='Tipo de dado', max_length=255),
        ),
        migrations.AlterField(
            model_name='record',
            name='product_status',
            field=models.CharField(choices=[('TRL 0 - Não iniciado', 'TRL 0 - Não iniciado'), ('TRL 1 - Princípios básicos observados e documentados', 'TRL 1 - Princípios básicos observados e documentados'), ('TRL 2 - Formulação do conceito da tecnologia', 'TRL 2 - Formulação do conceito da tecnologia'), ('TRL 3 - Prova de conceito experimental', 'TRL 3 - Prova de conceito experimental'), ('TRL 4 - Validação do conceito em laboratório', 'TRL 4 - Validação do conceito em laboratório'), ('TRL 5 - Validação do conceito em ambiente relevante', 'TRL 5 - Validação do conceito em ambiente relevante'), ('TRL 6 - Demonstração em ambiente relevante', 'TRL 6 - Demonstração em ambiente relevante'), ('TRL 7 - Demonstração em ambiente operacional', 'TRL 7 - Demonstração em ambiente operacional'), ('TRL 8 - Sistema completo e qualificado', 'TRL 8 - Sistema completo e qualificado'), ('TRL 9 - Sistema comprovado em ambiente operacional', 'TRL 9 - Sistema comprovado em ambiente operacional')], help_text='Status do produto', max_length=255),
        ),
    ]
