# Generated by Django 5.1.4 on 2025-02-08 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0015_remove_record_responsible_record_responsible_person_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='business_status',
            new_name='initial_maturity',
        ),
    ]
