# Generated by Django 5.1.4 on 2025-02-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0016_rename_business_status_record_initial_maturity'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='cycle',
            field=models.CharField(choices=[('Startup Piaui 1', 'Startup Piaui 1'), ('Startup Piaui 2', 'Startup Piaui 2'), ('Startup Piaui 3', 'Startup Piaui 3'), ('Startup Piaui 4', 'Startup Piaui 4'), ('Startup Piaui 5', 'Startup Piaui 5'), ('Startup Piaui 6', 'Startup Piaui 6'), ('Startup Piaui 7', 'Startup Piaui 7'), ('Batalha do Conhecimento 1', 'Batalha do Conhecimento 1'), ('Maratona de Negócios 1', 'Maratona de Negócios 1'), ('Batalha de Startups 1', 'Batalha de Startups 1'), ('Investe Nelas 1', 'Investe Nelas 1'), ('Investe Nelas 2', 'Investe Nelas 2'), ('Expo Favela 2024', 'Expo Favela 2024'), ('Expo Favela 2023', 'Expo Favela 2023')], default='Startup Piaui 1', help_text='Selecione o ciclo da sua startup', max_length=50),
        ),
        migrations.AddField(
            model_name='record',
            name='business_model',
            field=models.CharField(blank=True, choices=[('Não sei', 'Não sei'), ('Afiliados / Marketing de influência', 'Afiliados / Marketing de influência'), ('Conteúdo premium / Licenciamento de conteúdo / Educação on-line', 'Conteúdo premium / Licenciamento de conteúdo / Educação on-line'), ('Cooperativa', 'Cooperativa'), ('Software house', 'Software house'), ('E-commerce', 'E-commerce'), ('Marketplace', 'Marketplace'), ('SAAS - Software como serviço', 'SAAS - Software como serviço'), ('HAAS - Hardware como serviço', 'HAAS - Hardware como serviço'), ('Indústria: Fabricação e venda direta online ou offline', 'Indústria: Fabricação e venda direta online ou offline'), ('Educação on-line', 'Educação on-line'), ('Comércio Offline', 'Comércio Offline'), ('Serviço Offline', 'Serviço Offline'), ('Educação off-line', 'Educação off-line'), ('Intermediação de negócios', 'Intermediação de negócios'), ('Negócio social', 'Negócio social'), ('Publicidade', 'Publicidade'), ('Outros', 'Outros')], help_text='Selecione o modelo de negócio', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='cycle',
            field=models.CharField(choices=[('Startup Piaui 1', 'Startup Piaui 1'), ('Startup Piaui 2', 'Startup Piaui 2'), ('Startup Piaui 3', 'Startup Piaui 3'), ('Startup Piaui 4', 'Startup Piaui 4'), ('Startup Piaui 5', 'Startup Piaui 5'), ('Startup Piaui 6', 'Startup Piaui 6'), ('Startup Piaui 7', 'Startup Piaui 7'), ('Batalha do Conhecimento 1', 'Batalha do Conhecimento 1'), ('Maratona de Negócios 1', 'Maratona de Negócios 1'), ('Batalha de Startups 1', 'Batalha de Startups 1'), ('Investe Nelas 1', 'Investe Nelas 1'), ('Investe Nelas 2', 'Investe Nelas 2'), ('Expo Favela 2024', 'Expo Favela 2024'), ('Expo Favela 2023', 'Expo Favela 2023')], default='Startup Piaui 1', help_text='Selecione o ciclo da sua startup', max_length=50),
        ),
        migrations.AddField(
            model_name='record',
            name='market',
            field=models.CharField(blank=True, choices=[('Agricultura e Pecuária', 'Agricultura e Pecuária'), ('Alimentos e Bebidas', 'Alimentos e Bebidas'), ('Automotivo e Mobilidade', 'Automotivo e Mobilidade'), ('Capital e Investimentos', 'Capital e Investimentos'), ('Comércio eletrônico', 'Comércio eletrônico'), ('Comunicação e Mídia', 'Comunicação e Mídia'), ('Construção e Imóveis', 'Construção e Imóveis'), ('Crédito e Finanças', 'Crédito e Finanças'), ('Educação', 'Educação'), ('Energia', 'Energia'), ('Esportes e Lazer', 'Esportes e Lazer'), ('Gestão e Consultoria', 'Gestão e Consultoria'), ('Governo e Poder Público', 'Governo e Poder Público'), ('Hotelaria e Turismo', 'Hotelaria e Turismo'), ('Indústria e Transformação', 'Indústria e Transformação'), ('Jogos e Entretenimento', 'Jogos e Entretenimento'), ('Logística e Transportes', 'Logística e Transportes'), ('Moda e Vestuário', 'Moda e Vestuário'), ('Motores e Equipamentos', 'Motores e Equipamentos'), ('Óleo e Gás', 'Óleo e Gás'), ('Saúde', 'Saúde'), ('Bem Estar', 'Bem Estar'), ('Segurança e Defesa', 'Segurança e Defesa'), ('Seguros', 'Seguros'), ('Serviços profissionais', 'Serviços profissionais'), ('Meio ambiente', 'Meio ambiente'), ('Sustentabilidade', 'Sustentabilidade'), ('Tecnologia da Informação', 'Tecnologia da Informação'), ('Telecomunicações', 'Telecomunicações'), ('Varejo e Atacado', 'Varejo e Atacado'), ('Outro', 'Outro')], help_text='Selecione o mercado que sua startup atua', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='business_model',
            field=models.CharField(blank=True, choices=[('Não sei', 'Não sei'), ('Afiliados / Marketing de influência', 'Afiliados / Marketing de influência'), ('Conteúdo premium / Licenciamento de conteúdo / Educação on-line', 'Conteúdo premium / Licenciamento de conteúdo / Educação on-line'), ('Cooperativa', 'Cooperativa'), ('Software house', 'Software house'), ('E-commerce', 'E-commerce'), ('Marketplace', 'Marketplace'), ('SAAS - Software como serviço', 'SAAS - Software como serviço'), ('HAAS - Hardware como serviço', 'HAAS - Hardware como serviço'), ('Indústria: Fabricação e venda direta online ou offline', 'Indústria: Fabricação e venda direta online ou offline'), ('Educação on-line', 'Educação on-line'), ('Comércio Offline', 'Comércio Offline'), ('Serviço Offline', 'Serviço Offline'), ('Educação off-line', 'Educação off-line'), ('Intermediação de negócios', 'Intermediação de negócios'), ('Negócio social', 'Negócio social'), ('Publicidade', 'Publicidade'), ('Outros', 'Outros')], help_text='Selecione o modelo de negócio', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='market',
            field=models.CharField(blank=True, choices=[('Agricultura e Pecuária', 'Agricultura e Pecuária'), ('Alimentos e Bebidas', 'Alimentos e Bebidas'), ('Automotivo e Mobilidade', 'Automotivo e Mobilidade'), ('Capital e Investimentos', 'Capital e Investimentos'), ('Comércio eletrônico', 'Comércio eletrônico'), ('Comunicação e Mídia', 'Comunicação e Mídia'), ('Construção e Imóveis', 'Construção e Imóveis'), ('Crédito e Finanças', 'Crédito e Finanças'), ('Educação', 'Educação'), ('Energia', 'Energia'), ('Esportes e Lazer', 'Esportes e Lazer'), ('Gestão e Consultoria', 'Gestão e Consultoria'), ('Governo e Poder Público', 'Governo e Poder Público'), ('Hotelaria e Turismo', 'Hotelaria e Turismo'), ('Indústria e Transformação', 'Indústria e Transformação'), ('Jogos e Entretenimento', 'Jogos e Entretenimento'), ('Logística e Transportes', 'Logística e Transportes'), ('Moda e Vestuário', 'Moda e Vestuário'), ('Motores e Equipamentos', 'Motores e Equipamentos'), ('Óleo e Gás', 'Óleo e Gás'), ('Saúde', 'Saúde'), ('Bem Estar', 'Bem Estar'), ('Segurança e Defesa', 'Segurança e Defesa'), ('Seguros', 'Seguros'), ('Serviços profissionais', 'Serviços profissionais'), ('Meio ambiente', 'Meio ambiente'), ('Sustentabilidade', 'Sustentabilidade'), ('Tecnologia da Informação', 'Tecnologia da Informação'), ('Telecomunicações', 'Telecomunicações'), ('Varejo e Atacado', 'Varejo e Atacado'), ('Outro', 'Outro')], help_text='Selecione o mercado que sua startup atua', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='state',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], help_text='Selecione o estado', max_length=2, null=True),
        ),
    ]
