# Generated by Django 5.1.4 on 2025-02-10 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0017_enterprise_cycle_record_business_model_record_cycle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companymetrics',
            name='value_invested',
        ),
    ]
