# Generated by Django 5.1.4 on 2025-02-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0018_remove_companymetrics_value_invested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='revenue_model',
            field=models.CharField(blank=True, choices=[('Não sei', 'Não sei'), ('Afiliados', 'Afiliados'), ('Anúncio', 'Anúncio'), ('Assinatura', 'Assinatura'), ('Freemium', 'Freemium'), ('Licenciamento', 'Licenciamento'), ('Intermediação de Negócios', 'Intermediação de Negócios'), ('Pay per Use', 'Pay per Use'), ('Venda de Hardware ou produto físico', 'Venda de Hardware ou produto físico'), ('Venda Direta', 'Venda Direta'), ('Transacional', 'Transacional'), ('Outro', 'Outro')], help_text='Selecione o modelo de receita', max_length=255, null=True),
        ),
    ]
