# Generated by Django 5.1.4 on 2025-02-17 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0020_companymetrics_captable'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymetrics',
            name='current_capital',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Capital atual da empresa', max_digits=15, null=True),
        ),
    ]
