# Generated by Django 5.1.4 on 2025-02-17 02:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0021_companymetrics_current_capital'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymetrics',
            name='created_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Hora exata da criação do registro'),
            preserve_default=False,
        ),
    ]
