# Generated by Django 5.1.4 on 2025-02-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0023_enterprise_created_at_record_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymetrics',
            name='metric_month',
            field=models.CharField(blank=True, choices=[('JAN', 'JAN'), ('FEB', 'FEB'), ('MAR', 'MAR'), ('APR', 'APR'), ('MAI', 'MAI'), ('JUN', 'JUN'), ('JUL', 'JUL'), ('AGO', 'AGO'), ('SET', 'SET'), ('OUT', 'OUT'), ('NOV', 'NOV'), ('DEZ', 'DEZ')], help_text='Selecione o período', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='companymetrics',
            name='metric_year',
            field=models.IntegerField(blank=True, help_text='Selecione o ano', null=True),
        ),
        migrations.AddField(
            model_name='companymetrics',
            name='partners_count',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Quantidade de Sócios'),
        ),
    ]
